# Generated by Django 3.0.8 on 2020-07-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog', '0003_auto_20200717_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
